demo/config/routes.rb
Rails.application.routes.draw do

  root 'ports#index'

  resources :hamsters

  resources :ports
end

demo/app/models/hamster.rb
class Hamster < ActiveRecord::Base
end

demo/app/models/port.rb
class Port < ActiveRecord::Base

  validates_presence_of :name, message: 'Please enter a name for this port'
  validates_numericality_of :lat, :lng
  validates_inclusion_of :name, in: ['Pirates Cove', 'Cape of Danger']

  validate :has_a_cat


  def cats
    "hammy"
  end

  private

    def has_a_cat
      self.errors.add(:cats, "were not present")
    end
end

demo/app/models/ship.rb
class Ship < ActiveRecord::Base

end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demo/app/controllers/hamsters_controller.rb
class HamstersController < ApplicationController
  before_action :set_hamster, only: [:show, :edit, :update, :destroy]

  # GET /hamsters
  # GET /hamsters.json
  def index
    @hamsters = Hamster.all
  end

  # GET /hamsters/1
  # GET /hamsters/1.json
  def show
  end

  # GET /hamsters/new
  def new
    @hamster = Hamster.new
  end

  # GET /hamsters/1/edit
  def edit
  end

  # POST /hamsters
  # POST /hamsters.json
  def create
    @hamster = Hamster.new(hamster_params)

    respond_to do |format|
      if @hamster.save
        format.html { redirect_to @hamster, notice: 'Hamster was successfully created.' }
        format.json { render :show, status: :created, location: @hamster }
      else
        format.html { render :new }
        format.json { render json: @hamster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hamsters/1
  # PATCH/PUT /hamsters/1.json
  def update
    respond_to do |format|
      if @hamster.update(hamster_params)
        format.html { redirect_to @hamster, notice: 'Hamster was successfully updated.' }
        format.json { render :show, status: :ok, location: @hamster }
      else
        format.html { render :edit }
        format.json { render json: @hamster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hamsters/1
  # DELETE /hamsters/1.json
  def destroy
    @hamster.destroy
    respond_to do |format|
      format.html { redirect_to hamsters_url, notice: 'Hamster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hamster
      @hamster = Hamster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hamster_params
      params.require(:hamster).permit(:lat, :lng, :name, :weather, :description)
    end
end

demo/app/controllers/ports_controller.rb
class PortsController < ApplicationController
  before_action :set_port, only: [:show, :edit, :update, :destroy]

  # GET /ports
  # GET /ports.json
  def index
    @ports = Port.all
  end

  # GET /ports/1
  # GET /ports/1.json
  def show
  end

  # GET /ports/new
  def new
    @port = Port.new
  end

  # GET /ports/1/edit
  def edit
  end

  # POST /ports
  # POST /ports.json
  def create
    @port = Port.new(port_params)

    respond_to do |format|
      if @port.save
        format.html { redirect_to @port, notice: 'Port was successfully created.' }
        format.json { render :show, status: :created, location: @port }
      else
        format.html { render :new }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ports/1
  # PATCH/PUT /ports/1.json
  def update
    respond_to do |format|
      if @port.update(port_params)
        format.html { redirect_to @port, notice: 'Port was successfully updated.' }
        format.json { render :show, status: :ok, location: @port }
      else
        format.html { render :edit }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ports/1
  # DELETE /ports/1.json
  def destroy
    @port.destroy
    respond_to do |format|
      format.html { redirect_to ports_url, notice: 'Port was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_port
      @port = Port.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def port_params
      params.require(:port).permit(:lat, :lng, :name, :weather, :description)
    end
end

demo/app/controllers/ships_controller.rb
class ShipsController < ApplicationController

  before_filter :get_ships, only: [:index]
  before_filter :get_ship, only: [:show, :edit, :update]

  def index
      @ships = Ship.all
  end

  def show
    @ship = Ship.find params[:id]
  end

end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/hamsters_helper.rb
module HamstersHelper
end

demo/app/helpers/ports_helper.rb
module PortsHelper
end

demo/app/views/cats/feed.html.erb
Now feeding the cat!!!

<%= @name %>

demo/app/views/cats/index.html.erb
<h1><%= @name %></h1>

<p>Hello World!!!</p>

<%= link_to :cats do %>Cats!<%end%>

demo/app/views/cats/show.html.erb
<h1>Showing a cat: <%= @cat_name %></h1>

demo/app/views/hamsters/_form.html.erb
<%= form_for(@hamster) do |f| %>
  <% if @hamster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hamster.errors.count, "error") %> prohibited this hamster from being saved:</h2>

      <ul>
      <% @hamster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br>
    <%= f.number_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.number_field :lng %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weather %><br>
    <%= f.text_field :weather %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/hamsters/edit.html.erb
<h1>Editing hamster</h1>

<%= render 'form' %>

<%= link_to 'Show', @hamster %> |
<%= link_to 'Back', hamsters_path %>

demo/app/views/hamsters/index.html.erb
<h1>Listing hamsters</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th>Name</th>
      <th>Weather</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hamsters.each do |hamster| %>
      <tr>
        <td><%= hamster.lat %></td>
        <td><%= hamster.lng %></td>
        <td><%= hamster.name %></td>
        <td><%= hamster.weather %></td>
        <td><%= hamster.description %></td>
        <td><%= link_to 'Show', hamster %></td>
        <td><%= link_to 'Edit', edit_hamster_path(hamster) %></td>
        <td><%= link_to 'Destroy', hamster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hamster', new_hamster_path %>

demo/app/views/hamsters/new.html.erb
<h1>New hamster</h1>

<%= render 'form' %>

<%= link_to 'Back', hamsters_path %>

demo/app/views/hamsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @hamster.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @hamster.lng %>
</p>

<p>
  <strong>Name:</strong>
  <%= @hamster.name %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @hamster.weather %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hamster.description %>
</p>

<%= link_to 'Edit', edit_hamster_path(@hamster) %> |
<%= link_to 'Back', hamsters_path %>

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloWorld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'layouts/partials/header' %>

<article>
  <%= yield %>
</article>


</body>
</html>

demo/app/views/layouts/blank.html.erb
<%= yield %>

demo/app/views/layouts/cats.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloWorld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'layouts/partials/header' %>

<article>
  <%= yield %>
</article>

<footer>
Cats
</footer>

</body>
</html>

demo/app/views/layouts/partials/_header.html.erb
<header>
  <h1>
    This is the page!!!
  </h1>
</header>

demo/app/views/ports/_form.html.erb
<%= form_for(@port) do |f| %>
  <% if @port.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@port.errors.count, "error") %> prohibited this port from being saved:</h2>

      <ul>
      <% @port.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br>
    <%= f.number_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.number_field :lng %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weather %><br>
    <%= f.text_field :weather %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/ports/edit.html.erb
<h1>Editing port</h1>

<%= render 'form' %>

<%= link_to 'Show', @port %> |
<%= link_to 'Back', ports_path %>

demo/app/views/ports/index.csv.erb
Lat, Lng, Name, Weather, Description
<% @ports.each do |port| %>
  <%= port.lat %>, <%= port.lng %>, <%= port.name %>, <%= port.weather %>, <%= port.description %>
<% end %>

demo/app/views/ports/index.html.erb
<h1>Listing ports</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th>Name</th>
      <th>Weather</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ports.each do |port| %>
      <tr>
        <td><%= port.lat %></td>
        <td><%= port.lng %></td>
        <td><%= port.name %></td>
        <td><%= port.weather %></td>
        <td><%= port.description %></td>
        <td><%= link_to 'Show', port %></td>
        <td><%= link_to 'Edit', edit_port_path(port) %></td>
        <td><%= link_to 'Destroy', port, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Port', new_port_path %>

demo/app/views/ports/new.html.erb
<h1>New port</h1>

<%= render 'form' %>

<%= link_to 'Back', ports_path %>

demo/app/views/ports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>My Lat:</strong>
  <%= @port.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @port.lng %>
</p>

<p>
  <strong>Name:</strong>
  <%= @port.name %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @port.weather %>
</p>

<p>
  <strong>Description:</strong>
  <%= @port.description %>
</p>

<p>
  <strong>Cat:</strong>
  <%= @port.cats %>
</p>

<%= link_to 'Edit', edit_port_path(@port) %> |
<%= link_to 'Back', ports_path %>